export const dataComponentNames = [
  'Service Creation',
  'Instance Enumeration',
  'Firewall Rule Modification',
  'Logon Session Metadata',
  'Cloud Storage Modification',
  'Cloud Storage Metadata',
  'User Account Creation',
  'Firewall Disable',
  'Cloud Storage Deletion',
  'Active Directory Object Deletion',
  'Network Communication',
  'Passive DNS',
  'Process Creation',
  'Active Directory Credential Request',
  'Service Metadata',
  'Cloud Storage Access',
  'Script Execution',
  'Module Load',
  'Cloud Service Enumeration',
  'Process Metadata',
  'Windows Registry Key Access',
  'Active Directory Object Creation',
  'Active Directory Object Access',
  'Network Traffic Flow',
  'Device Alarm',
  'Group Metadata',
  'Container Enumeration',
  'Network Traffic Content',
  'User Account Deletion',
  'File Access',
  'Drive Access',
  'Application Assets',
  'Kernel Module Load',
  'Application Log Content',
  'Volume Deletion',
  'Volume Creation',
  'Windows Registry Key Creation',
  'Service Modification',
  'Container Metadata',
  'Instance Start',
  'Volume Modification',
  'Malware Content',
  'Image Metadata',
  'Pod Enumeration',
  'Container Creation',
  'Certificate Registration',
  'Process Termination',
  'File Metadata',
  'Permissions Requests',
  'Social Media',
  'Permissions Request',
  'Response Content',
  'Software',
  'Scheduled Job Metadata',
  'Windows Registry Key Deletion',
  'Snapshot Creation',
  'Snapshot Deletion',
  'WMI Creation',
  'Cloud Service Modification',
  'Windows Registry Key Modification',
  'Pod Modification',
  'User Account Metadata',
  'Asset Inventory',
  'User Account Authentication',
  'Scheduled Job Creation',
  'Driver Load',
  'Snapshot Modification',
  'Image Modification',
  'Group Enumeration',
  'Volume Metadata',
  'Firmware Modification',
  'System Settings',
  'Process/Event Alarm',
  'Instance Modification',
  'Instance Creation',
  'API Calls',
  'Malware Metadata',
  'Drive Modification',
  'OS API Execution',
  'Scheduled Job Modification',
  'Process Access',
  'Process Modification',
  'System Notifications',
  'Network Connection Creation',
  'Response Metadata',
  'Active DNS',
  'Image Deletion',
  'Web Credential Creation',
  'Instance Deletion',
  'Cloud Service Metadata',
  'Host Status',
  'Cloud Storage Enumeration',
  'Process History/Live Data',
  'Cloud Storage Creation',
  'Web Credential Usage',
  'User Account Modification',
  'Named Pipe Metadata',
  'Volume Enumeration',
  'Container Start',
  'Network Share Access',
  'Domain Registration',
  'File Modification',
  'Protected Configuration',
  'Firewall Enumeration',
  'Cloud Service Disable',
  'File Deletion',
  'Driver Metadata',
  'Active Directory Object Modification',
  'Drive Creation',
  'Command Execution',
  'File Creation',
  'Logon Session Creation',
  'Pod Metadata',
  'Cluster Metadata',
  'Snapshot Enumeration',
  'Pod Creation',
  'Group Modification',
  'Instance Stop',
  'Snapshot Metadata',
  'Instance Metadata',
  'Image Creation',
  'Firewall Metadata',
];
